"""empty message

Revision ID: 07b0091e6caf
Revises: 478e5f266a8a
Create Date: 2026-01-29 02:40:24.647900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b0091e6caf'
down_revision = '478e5f266a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCharacter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed', sa.NVARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCharacter', schema=None) as batch_op:
        batch_op.drop_column('fixed')

    # ### end Alembic commands ###
