"""empty message

Revision ID: 0f419f1213e1
Revises: 73f37ae85042
Create Date: 2026-01-13 22:37:29.294035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f419f1213e1'
down_revision = '73f37ae85042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GFormula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combination', sa.NVARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_assembly_material'), type_='foreignkey')
        batch_op.create_foreign_key('fk_combination_material', 'GMaterial', ['combination'], ['materialcode'])
        batch_op.drop_column('assembly')

    with op.batch_alter_table('GInventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GInventory', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('GFormula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assembly', sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_combination_material', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_assembly_material'), 'GMaterial', ['assembly'], ['materialcode'])
        batch_op.drop_column('combination')

    # ### end Alembic commands ###
