"""empty message

Revision ID: 3c8ab5e4bacb
Revises: 5b9fede768b8
Create Date: 2026-01-27 14:38:34.444362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8ab5e4bacb'
down_revision = '5b9fede768b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.alter_column('sequenceid',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.alter_column('sequenceid',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###
