"""empty message

Revision ID: 478e5f266a8a
Revises: 3c8ab5e4bacb
Create Date: 2026-01-27 15:12:13.150230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478e5f266a8a'
down_revision = '3c8ab5e4bacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__GCraft__departme__634EBE90'), type_='foreignkey')
        batch_op.drop_column('department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('FK__GCraft__departme__634EBE90'), 'GCharacter', ['department'], ['charactercode'])

    # ### end Alembic commands ###
