"""empty message

Revision ID: 5b9fede768b8
Revises: a0e14f438c3e
Create Date: 2026-01-27 14:33:57.618723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9fede768b8'
down_revision = 'a0e14f438c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequenceid', sa.NVARCHAR(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'GSequence', ['sequenceid'], ['sequenceid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCraft', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sequenceid')

    # ### end Alembic commands ###
