"""empty message

Revision ID: 5c225b363fc8
Revises: f6dd08a8d3c5
Create Date: 2025-12-20 21:13:30.723856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c225b363fc8'
down_revision = 'f6dd08a8d3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPRLine', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('FK__GPRLine__prcode__08B54D69'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'GPRHeader', ['prcode'], ['prcode'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPRLine', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK__GPRLine__prcode__08B54D69'), 'GPRHeader', ['prcode'], ['prcode'])

    # ### end Alembic commands ###
