"""empty message

Revision ID: 73f37ae85042
Revises: 8f657e5ab09a
Create Date: 2026-01-03 19:48:52.039089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f37ae85042'
down_revision = '8f657e5ab09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=True)

    # ### end Alembic commands ###
