"""empty message

Revision ID: 8ddcd2adcc87
Revises: f7cc536930ae
Create Date: 2026-01-29 15:01:23.305905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddcd2adcc87'
down_revision = 'f7cc536930ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPItem', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPItem', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)

    # ### end Alembic commands ###
