"""empty message

Revision ID: 8f657e5ab09a
Revises: f53fba33e3d5
Create Date: 2026-01-03 19:45:52.445687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f657e5ab09a'
down_revision = 'f53fba33e3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.NVARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
