"""empty message

Revision ID: 97656a28bc8a
Revises: 5c225b363fc8
Create Date: 2026-01-02 21:42:24.625392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97656a28bc8a'
down_revision = '5c225b363fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.drop_column('willreceive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('willreceive', sa.DATETIME(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
