"""empty message

Revision ID: a0e14f438c3e
Revises: 2888f882280d
Create Date: 2026-01-23 09:23:33.563801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e14f438c3e'
down_revision = '2888f882280d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GSOHeader', schema=None) as batch_op:
        batch_op.drop_column('altertime')
        batch_op.drop_column('alteruser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GSOHeader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alteruser', sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('altertime', sa.DATETIME(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
