"""empty message

Revision ID: a19db3f0bab0
Revises: 0f419f1213e1
Create Date: 2026-01-13 22:46:59.876503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19db3f0bab0'
down_revision = '0f419f1213e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GFormula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('craftid', sa.NVARCHAR(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'GCraft', ['craftid'], ['craftid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GFormula', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('craftid')

    # ### end Alembic commands ###
