"""empty message

Revision ID: bc1175773fa7
Revises: f581016288c9
Create Date: 2026-03-07 21:05:16.135079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1175773fa7'
down_revision = 'f581016288c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPRHeader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opinion', sa.NVARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPRHeader', schema=None) as batch_op:
        batch_op.drop_column('opinion')

    # ### end Alembic commands ###
