"""empty message

Revision ID: f53fba33e3d5
Revises: 97656a28bc8a
Create Date: 2026-01-02 22:01:41.687436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53fba33e3d5'
down_revision = '97656a28bc8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pocode', sa.NVARCHAR(length=50), nullable=False))
        batch_op.alter_column('warehousecode',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=True)
        batch_op.create_foreign_key(None, 'GPOHeader', ['pocode'], ['pocode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GReceipt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('warehousecode',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=False)
        batch_op.drop_column('pocode')

    # ### end Alembic commands ###
