"""empty message

Revision ID: f581016288c9
Revises: f8a2155e4bff
Create Date: 2026-02-05 01:08:55.172977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f581016288c9'
down_revision = 'f8a2155e4bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPReport', schema=None) as batch_op:
        batch_op.drop_column('reviewquantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPReport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewquantity', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
