"""empty message

Revision ID: f6dd08a8d3c5
Revises: 
Create Date: 2025-12-20 13:37:52.734643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dd08a8d3c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GCharacter', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=True)

    with op.batch_alter_table('GMaterial', schema=None) as batch_op:
        batch_op.alter_column('materialtype',
               existing_type=sa.NVARCHAR(length=10, collation='Chinese_PRC_CI_AS'),
               type_=sa.NVARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GMaterial', schema=None) as batch_op:
        batch_op.alter_column('materialtype',
               existing_type=sa.NVARCHAR(length=50),
               type_=sa.NVARCHAR(length=10, collation='Chinese_PRC_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('GCharacter', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.NVARCHAR(length=50, collation='Chinese_PRC_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
