"""empty message

Revision ID: f7cc536930ae
Revises: 07b0091e6caf
Create Date: 2026-01-29 14:53:06.108035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cc536930ae'
down_revision = '07b0091e6caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Numeric(precision=18, scale=6), nullable=True))
        batch_op.add_column(sa.Column('itemqr', sa.NVARCHAR(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPItem', schema=None) as batch_op:
        batch_op.drop_column('itemqr')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
