"""empty message

Revision ID: f8a2155e4bff
Revises: 8ddcd2adcc87
Create Date: 2026-02-05 00:51:24.623029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a2155e4bff'
down_revision = '8ddcd2adcc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPReport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realquantity', sa.Numeric(precision=18, scale=6), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GPReport', schema=None) as batch_op:
        batch_op.drop_column('realquantity')

    # ### end Alembic commands ###
